GUI_UID=1000   # The UID of the user allowed to run GUI components (typically a normal desktop user)
RUST_LOG=info  # logging level for passkeyd

# Advanced option: The front-end UI for for passkey creation
FRONT_ENROLL=passkeyd-enroll  

# Advanced option: The front-end UI for selecting a passkey
FRONT_SELECT=passkeyd-select 

# Advanced option: The front-end UI for verifying the user's presence.
FRONT_SELECTION=passkeyd-selection 