GUI_UID=1000   # The UID of the user allowed to run GUI components (typically a normal desktop user)
RUST_LOG=info  # logging level for passkeyd

# Advanced option: The front-end UI for for passkey creation
FRONT_ENROLL=/usr/lib/passkeyd/passkeyd-enroll 

# Advanced option: The front-end UI for selecting a passkey
FRONT_SELECT=/usr/lib/passkeyd/passkeyd-select

# Advanced option: The front-end UI for verifying the user's presence.
FRONT_SELECTION=/usr/lib/passkeyd/passkeyd-selection

# There are two modes for cryptography:
# 1. TPM (Highly recommended) => Fancy math is done at the hardware level (no one can sneak in, no one can access private data)
# 2. Virtual => Fancy math is done at the software level, without hardware support.

# It is 'HIGHLY' recommended to use TPM-based cryptography.

# IMPORTANT: NON-TPM KEYS ARE NOT ENCRYPTED AND ARE EXPOSED.
# HOWEVER, they are stored with root privileges, so no one can access them without root access.

# SUPER, SUPER, REALLY IMPORTANT:
# YOU MUST HAVE TPM 2.0 IN ORDER TO USE TPM.
# You can check this with the command `ls /dev/tpm*`.
# If this returns nothing, either you don't have TPM or it isn't functioning properly.
# You might want to switch to virtual cryptography.

USE_TPM_CRYPTOGRAPHY=yes # Can either be "yes" or "no"

# The language is automatically selected based on system preferences, but can be forced to switch via this option.
# Available language options:
# de, en, fr, ru, zh
# LANGUAGE=eu