# Format: [r, g, b, a]  
# Each value must be between 0-255.  
# 'r' represents the red channel  
# 'g' represents the green channel  
# 'b' represents the blue channel  
# 'a' represents the alpha channel, which determines the transparency of the color.

background = [36, 37, 50, 255]  # Background color (dark shade)
primary_text = [255, 255, 255, 255]  # Primary text color (for title, approval buttons)
secondary_text = [230, 230, 230, 255]  # Secondary text color (for descriptions)
surface = [45, 40, 60, 255]  # Surface color (used for elevated surfaces)
surface_primary_text = [236, 217, 217, 255]  # Text color for site name within elevated surfaces
surface_secondary_text = [236, 217, 217, 255]  # Text color for site username within elevated surfaces
accent = [160, 135, 255, 255]  # Accent color (used for button backgrounds)
scrollbar_track = [115, 115, 115, 25]  # Scrollbar track color (background of the scrollbar)
scrollbar_thumb = [80, 80, 80, 90]  # Scrollbar thumb color (movable part of the scrollbar)